baseurl = "http://careers.fivewalls.com/"
languageCode = "en-us"
title = "Fivewalls Careers"
theme = "fivewalls"
CopyRight = '''
The trademarks REALTOR&reg;, REALTORS&reg; and the REALTOR&reg; logo are controlled by The Canadian Real Estate Association (CREA)
and identify real estate professionals who are members of CREA. The trademarks MLS&reg;, Multiple Listing Service&reg; and the
associated logos are owned by CREA and identify the quality of services provided by real estate professionals who are
members of CREA.

Copyright 2015 fivewalls realty. All Rights Reserved.'''
[Params]
gaid = "UA-64925014-5"
